services:
  postgres_taller_db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres
    container_name: postgres_taller_db
    restart: always
    environment:
      POSTGRES_DB: postgres_taller_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_taller_db:/var/lib/postgresql/data
      - ./.data:/data